[phases.setup]
nixPkgs = ["python313", "uv"]

[phases.install]
cmds = ["uv sync --frozen --no-dev"]

[start]
cmd = "uv run flask run --host=0.0.0.0 --port=5000"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
FLASK_APP = "src.web.app"
